import os
import logging
import psycopg2
from psycopg2.extras import RealDictCursor

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

DATABASE_URL = os.getenv("DATABASE_URL")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ==========================================
# DATABASE CONNECTION
# ==========================================

def get_connection():
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL is missing. Configure PostgreSQL connection."
        )

    return psycopg2.connect(
        DATABASE_URL,
        cursor_factory=RealDictCursor,
        connect_timeout=15
    )


# ==========================================
# CREATE HISTORY TABLE
# ==========================================

def create_history_table():
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS prediction_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    song TEXT NOT NULL,
                    mood TEXT NOT NULL,
                    confidence TEXT NOT NULL,
                    intensity TEXT NOT NULL,
                    date TEXT NOT NULL
                )
            """)

        conn.commit()
        logger.info("PostgreSQL prediction history table is ready.")

    except Exception:
        conn.rollback()
        logger.exception("Failed to create PostgreSQL history table.")
        raise

    finally:
        conn.close()


# ==========================================
# SAVE PREDICTION
# ==========================================

def save_prediction(song, mood, confidence, intensity, date):
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                INSERT INTO prediction_history
                    (song, mood, confidence, intensity, date)
                VALUES (%s, %s, %s, %s, %s)
                RETURNING id
            """, (
                str(song),
                str(mood),
                str(confidence),
                str(intensity),
                str(date)
            ))

            prediction_id = cursor.fetchone()["id"]

        conn.commit()

        logger.info(
            "Prediction saved. ID=%s, Song=%s, Mood=%s",
            prediction_id, song, mood
        )

        return prediction_id

    except Exception:
        conn.rollback()
        logger.exception("Failed to save prediction for song: %s", song)
        raise

    finally:
        conn.close()


# ==========================================
# GET ALL PREDICTIONS
# ==========================================

def get_predictions():
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT id, song, mood, confidence, intensity, date
                FROM prediction_history
                ORDER BY id DESC
            """)

            predictions = [dict(row) for row in cursor.fetchall()]

        logger.info("Retrieved %s prediction records.", len(predictions))
        return predictions

    except Exception:
        logger.exception("Failed to retrieve prediction history.")
        raise

    finally:
        conn.close()


# ==========================================
# DELETE ONE PREDICTION
# ==========================================

def delete_prediction(prediction_id):
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                DELETE FROM prediction_history
                WHERE id = %s
            """, (prediction_id,))

            deleted_count = cursor.rowcount

        conn.commit()
        return deleted_count

    except Exception:
        conn.rollback()
        logger.exception("Failed to delete prediction ID=%s", prediction_id)
        raise

    finally:
        conn.close()


# ==========================================
# CLEAR ALL PREDICTIONS
# ==========================================

def clear_predictions():
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("DELETE FROM prediction_history")
            deleted_count = cursor.rowcount

        conn.commit()
        logger.info("Cleared %s prediction records.", deleted_count)
        return deleted_count

    except Exception:
        conn.rollback()
        logger.exception("Failed to clear prediction history.")
        raise

    finally:
        conn.close()


# ==========================================
# INITIALIZE DATABASE
# ==========================================

create_history_table()
