
import os
import logging
import psycopg2
from psycopg2.extras import RealDictCursor

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

DATABASE_URL = os.getenv("DATABASE_URL")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ==========================================
# DATABASE CONNECTION
# ==========================================

def get_connection():
    database_url = os.getenv("DATABASE_URL") or DATABASE_URL

    if not database_url:
        raise RuntimeError(
            "DATABASE_URL is missing. Configure PostgreSQL connection."
        )

    return psycopg2.connect(
        database_url,
        cursor_factory=RealDictCursor,
        connect_timeout=15
    )


# ==========================================
# CREATE DATABASE TABLES
# ==========================================

def create_history_table():
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS prediction_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    song TEXT NOT NULL,
                    mood TEXT NOT NULL,
                    confidence TEXT NOT NULL,
                    intensity TEXT NOT NULL,
                    date TEXT NOT NULL
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS user_feedback (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    song_name TEXT,
                    mood TEXT,
                    confidence TEXT,
                    helpfulness TEXT NOT NULL,
                    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
                    feedback TEXT,
                    submitted_at TEXT
                )
            """)

        conn.commit()
        logger.info("PostgreSQL tables are ready.")

    except Exception:
        conn.rollback()
        logger.exception("Failed to create database tables.")
        raise

    finally:
        conn.close()


# ==========================================
# SAVE PREDICTION
# ==========================================

def save_prediction(song, mood, confidence, intensity, date):
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                INSERT INTO prediction_history
                    (song, mood, confidence, intensity, date)
                VALUES (%s, %s, %s, %s, %s)
                RETURNING id
            """, (
                str(song),
                str(mood),
                str(confidence),
                str(intensity),
                str(date)
            ))

            prediction_id = cursor.fetchone()["id"]

        conn.commit()

        logger.info(
            "Prediction saved. ID=%s, Song=%s, Mood=%s",
            prediction_id, song, mood
        )

        return prediction_id

    except Exception:
        conn.rollback()
        logger.exception("Failed to save prediction for song: %s", song)
        raise

    finally:
        conn.close()


# ==========================================
# GET ALL PREDICTIONS
# ==========================================

def get_predictions():
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                SELECT id, song, mood, confidence, intensity, date
                FROM prediction_history
                ORDER BY id DESC
            """)

            predictions = [dict(row) for row in cursor.fetchall()]

        logger.info("Retrieved %s prediction records.", len(predictions))
        return predictions

    except Exception:
        logger.exception("Failed to retrieve prediction history.")
        raise

    finally:
        conn.close()


# ==========================================
# DELETE ONE PREDICTION
# ==========================================

def delete_prediction(prediction_id):
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("""
                DELETE FROM prediction_history
                WHERE id = %s
            """, (prediction_id,))

            deleted_count = cursor.rowcount

        conn.commit()
        return deleted_count

    except Exception:
        conn.rollback()
        logger.exception("Failed to delete prediction ID=%s", prediction_id)
        raise

    finally:
        conn.close()


# ==========================================
# CLEAR ALL PREDICTIONS
# ==========================================

def clear_predictions():
    conn = get_connection()

    try:
        with conn.cursor() as cursor:
            cursor.execute("DELETE FROM prediction_history")
            deleted_count = cursor.rowcount

        conn.commit()
        logger.info("Cleared %s prediction records.", deleted_count)
        return deleted_count

    except Exception:
        conn.rollback()
        logger.exception("Failed to clear prediction history.")
        raise

    finally:
        conn.close()


# ==========================================
# SAVE USER FEEDBACK
# ==========================================

def save_feedback(feedback_data):
    conn = get_connection()

    try:
        helpfulness = str(feedback_data.get("helpfulness", "")).strip()
        rating = int(feedback_data.get("rating", 0))

        if not helpfulness:
            raise ValueError("Feedback helpfulness is required.")

        if rating < 1 or rating > 5:
            raise ValueError("Rating must be between 1 and 5.")

        with conn.cursor() as cursor:
            cursor.execute("""
                INSERT INTO user_feedback (
                    song_name,
                    mood,
                    confidence,
                    helpfulness,
                    rating,
                    feedback,
                    submitted_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING id
            """, (
                str(feedback_data.get("songName", "")),
                str(feedback_data.get("mood", "")),
                str(feedback_data.get("confidence", "")),
                helpfulness,
                rating,
                str(feedback_data.get("feedback", "")),
                str(feedback_data.get("submittedAt", ""))
            ))

            feedback_id = cursor.fetchone()["id"]

        conn.commit()

        logger.info("Feedback saved successfully. ID=%s", feedback_id)
        return feedback_id

    except Exception:
        conn.rollback()
        logger.exception("Failed to save user feedback.")
        raise

    finally:
        conn.close()


# ==========================================
# INITIALIZE DATABASE TABLES
# ==========================================

create_history_table()
